# Generated by Django 4.0.6 on 2022-11-06 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(help_text='Required and Unique', max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Customer id')),
                ('name', models.CharField(help_text='String name', max_length=255, verbose_name='Customer name')),
                ('email', models.CharField(help_text='String email', max_length=255, verbose_name='Customer email')),
                ('profile_image', models.CharField(help_text='String url of image', max_length=255, verbose_name='Customer profile Image')),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(help_text='auto increment, int id', primary_key=True, serialize=False, unique=True, verbose_name='FoodCategory id')),
                ('c_name', models.CharField(help_text='Required', max_length=300, verbose_name='Category Name')),
                ('image_id', models.URLField(help_text='https://my_image.png', max_length=500, verbose_name='Food Image Url')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.CharField(help_text='Required and Unique', max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Provider id ')),
                ('name', models.CharField(help_text=' Required ', max_length=255, verbose_name='Provider name')),
                ('location', models.CharField(help_text=' Required , (lat, lng) ', max_length=100, verbose_name='Provider location')),
                ('image_id', models.CharField(help_text='https://my_image.png', max_length=255, verbose_name='Provider Profile Image Url')),
                ('known_for', models.CharField(help_text=' Not Required', max_length=100, verbose_name='famous food ')),
                ('open_time', models.CharField(help_text='10:00 AM', max_length=100, verbose_name='Provider open time ')),
                ('close_time', models.CharField(help_text='10:00 PM', max_length=100, verbose_name='Provider close time ')),
                ('created_at', models.CharField(help_text='Timesamp take default timestamp', max_length=255, verbose_name='Account created timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='UserScan',
            fields=[
                ('id', models.AutoField(help_text='Auto increment int', primary_key=True, serialize=False, unique=True, verbose_name='UserScan id ')),
                ('scan_url', models.URLField(help_text='https://myhotel.com/tara_hotel/account', max_length=500, verbose_name='Scanned Url')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Scanned at')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scan', to='edering.customer', verbose_name='Scanned customer')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(help_text='auto increment, int id', primary_key=True, serialize=False, unique=True, verbose_name='rating id')),
                ('rating', models.DecimalField(decimal_places=3, help_text='decimal valued rating', max_digits=10, verbose_name='rating_value')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='time stamp value', verbose_name='date created_at')),
                ('rating_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_from', to='edering.customer', verbose_name='Customer')),
                ('rating_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='edering.provider', verbose_name='Provider')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(help_text='auto increment, int id', primary_key=True, serialize=False, unique=True, verbose_name='Order id')),
                ('food_name', models.CharField(help_text='Not Required', max_length=255, verbose_name='food name ')),
                ('food_count', models.IntegerField(help_text='Not Required', verbose_name='food count ')),
                ('order_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Ordered at')),
                ('order_status', models.CharField(help_text='Canceled, approved ... ', max_length=255, verbose_name='Order Status')),
                ('order_cost', models.DecimalField(decimal_places=3, help_text='Total cost of order', max_digits=10, verbose_name='Order cost')),
                ('order_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='edering.customer', verbose_name='Order from')),
                ('order_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_order', to='edering.provider', verbose_name='Order to')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(help_text='auto increment, int id', primary_key=True, serialize=False, unique=True, verbose_name='Menu id')),
                ('name', models.CharField(help_text='Required', max_length=100, verbose_name='Menu item name')),
                ('price', models.DecimalField(decimal_places=3, help_text='Decimal Digit', max_digits=10, verbose_name='Menu Item price')),
                ('image_url', models.CharField(help_text='String url of image', max_length=255, verbose_name='Menu Image')),
                ('foodCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='edering.foodcategory', verbose_name='Food Category')),
            ],
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_categories', to='edering.provider', verbose_name='provider'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(help_text='auto increment, int id', primary_key=True, serialize=False, unique=True, verbose_name='Comment id')),
                ('content', models.TextField(verbose_name='Comment conent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Commented at')),
                ('comment_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_comment_from', to='edering.customer', verbose_name='Comment customer')),
                ('comment_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='edering.provider', verbose_name='Comment Hotel')),
            ],
        ),
    ]
