# Generated by Django 4.0.6 on 2022-07-31 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(help_text='Required and Unique', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Customer id ')),
                ('auth_id', models.CharField(help_text='Required and Unique', max_length=100, unique=True, verbose_name='Firebase auth id ')),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.CharField(help_text='Required and Unique', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='FoodCategory id ')),
                ('c_name', models.CharField(help_text='Required', max_length=300, verbose_name='Category Name')),
                ('image_uri_id', models.URLField(help_text='https://my_image.png', max_length=500, verbose_name='Food Image Url')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.CharField(help_text='Required and Unique', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='hotel id ')),
                ('name', models.CharField(help_text=' Required ', max_length=300, verbose_name='hotel name')),
                ('location', models.CharField(help_text=' Required , (lat, lng) ', max_length=100, verbose_name='hotel location')),
                ('image_uri_id', models.URLField(help_text='https://my_image.png', max_length=500, verbose_name='Hotel Profile Image Url')),
                ('known_for', models.CharField(help_text=' Not Required', max_length=100, verbose_name='famous food ')),
                ('rating', models.FloatField(help_text=' Required , (lat, lng) ', verbose_name='hotel location')),
                ('open_time', models.CharField(help_text='10:00 AM', max_length=100, verbose_name='Hotel open time ')),
                ('close_time', models.CharField(help_text='10:00 PM', max_length=100, verbose_name='Hotel close time ')),
                ('account_create', models.CharField(help_text='Timesamp take default timestamp', max_length=300, verbose_name='Account created timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.CharField(help_text='Required and Unique', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Menu id ')),
                ('name', models.CharField(help_text='Required', max_length=100, verbose_name='Menu item name')),
                ('price', models.CharField(help_text='Required and Unique', max_length=100, verbose_name='Menu Item price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='edering.foodcategory', verbose_name='Food Category id')),
            ],
        ),
        migrations.CreateModel(
            name='UserScan',
            fields=[
                ('id', models.UUIDField(help_text='Required and Unique', primary_key=True, serialize=False, unique=True, verbose_name='UserScan id ')),
                ('scan_url', models.URLField(help_text='https://myhotel.com/tara_hotel/account', max_length=500, verbose_name='Scanned Url')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Scanned at')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userscan_user_id', to='edering.customer', verbose_name='Scanned customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(help_text='Required and Unique', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='order id ')),
                ('order_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Ordered at')),
                ('delivered_status', models.BooleanField(default=False, help_text='True', verbose_name='Served status')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_food', to='edering.menu', verbose_name='Ordered food item')),
                ('order_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_order_form', to='edering.customer', verbose_name='Ordered customer')),
                ('order_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_order_to', to='edering.hotel', verbose_name='Ordered Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(help_text='Required and Unique', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Comment Id')),
                ('content', models.TextField(verbose_name='Comment conent')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Commented at')),
                ('comment_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_comment_from', to='edering.customer', verbose_name='Comennt customer')),
                ('comment_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_comment_to', to='edering.hotel', verbose_name='Comment Hotel')),
            ],
        ),
    ]
