# Generated by Django 4.0.6 on 2022-11-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscan',
            name='scan_url',
            field=models.CharField(help_text='https://myhotel.com/tara_hotel/account', max_length=255, verbose_name='Scanned Url'),
        ),
    ]
