# Generated by Django 4.0.6 on 2022-10-24 14:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edering', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='foodcategory',
            old_name='image_uri_id',
            new_name='image_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='menu',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='edering.menu', verbose_name='Menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='food_count',
            field=models.IntegerField(default=1, help_text='Not Required', verbose_name='food count '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='food_name',
            field=models.CharField(default='', help_text='Not Required', max_length=255, verbose_name='food name '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_comment_from', to='edering.customer', verbose_name='Comment customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='edering.customer', verbose_name='Ordered customer'),
        ),
        migrations.AlterField(
            model_name='userscan',
            name='id',
            field=models.CharField(help_text='Required and Unique', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='UserScan id '),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.CharField(help_text='Required and Unique', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='hotel id ')),
                ('name', models.CharField(help_text=' Required ', max_length=300, verbose_name='hotel name')),
                ('location', models.CharField(help_text=' Required , (lat, lng) ', max_length=100, verbose_name='hotel location')),
                ('image_id', models.URLField(help_text='https://my_image.png', max_length=500, verbose_name='Hotel Profile Image Url')),
                ('known_for', models.CharField(help_text=' Not Required', max_length=100, verbose_name='famous food ')),
                ('rating', models.FloatField(help_text='4.5', verbose_name='Hotel Rating')),
                ('open_time', models.CharField(help_text='10:00 AM', max_length=100, verbose_name='Hotel open time ')),
                ('close_time', models.CharField(help_text='10:00 PM', max_length=100, verbose_name='Hotel close time ')),
                ('created_at', models.CharField(help_text='Timesamp take default timestamp', max_length=300, verbose_name='Account created timestamp')),
                ('foods_categroies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='edering.foodcategory', verbose_name='foods')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_comment_to', to='edering.provider', verbose_name='Comment Hotel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_id', to='edering.provider', verbose_name='Ordered Hotel'),
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
