# Generated by Django 4.0.6 on 2022-10-25 13:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edering', '0002_rename_date_time_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='foods_categroies',
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='provider',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='edering.provider', verbose_name='provider'),
            preserve_default=False,
        ),
    ]
