# Generated by Django 4.0.6 on 2022-10-28 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edering', '0002_provider_rename_date_time_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='edering.provider', verbose_name='Comment Hotel'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='to_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='edering.provider', verbose_name='Provider'),
        ),
    ]
