# Generated by Django 4.0.6 on 2022-10-25 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edering', '0003_remove_foodcategory_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='foodCategory',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='food_categories', to='edering.foodcategory', verbose_name='Menu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_categories', to='edering.provider', verbose_name='provider'),
        ),
    ]
