# Generated by Django 4.0.6 on 2022-10-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edering', '0003_alter_comment_comment_to_alter_rating_to_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='time stamp value', verbose_name='date created_at'),
        ),
    ]
