# Generated by Django 4.0.6 on 2022-10-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edering', '0005_remove_provider_rating_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='image_id',
            field=models.CharField(help_text='https://my_image.png', max_length=255, verbose_name='Provider Profile Image Url'),
        ),
    ]
