# Generated by Django 4.0.6 on 2022-11-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edering', '0006_alter_provider_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='', help_text='String email', max_length=255, verbose_name='Customer email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', help_text='String name', max_length=255, verbose_name='Customer name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.CharField(default='', help_text='String url of image', max_length=255, verbose_name='Customer profile Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='image_url',
            field=models.CharField(default='', help_text='String url of image', max_length=255, verbose_name='Menu Image'),
            preserve_default=False,
        ),
    ]
